src/Entity/Gallery.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\GalleryRepository")
 */
class Gallery
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="gallery", cascade={"persist", "remove"})
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $path;

    public function __construct()
    {
        $this->date_creation = new \DateTime('now');
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(): self
    {
        $slugger = new Slugify();
        $this->slug = $slugger->slugify($this->getName());

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setGallery($this);
        }

        return $this;
    }

    public function resetImages()
    {
        $this->images = new ArrayCollection();
        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getGallery() === $this) {
                $image->setGallery(null);
            }
        }

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(): self
    {
        $this->path = $this->getDateCreation()->format('d-m-Y')."-".$this->getSlug() . "/";

        return $this;
    }
}

src/Controller/Administration/AdminController.php
<?php

namespace App\Controller\Administration;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class AdminController extends AbstractController
{
    /**
     * @Route("/", name="administration")
     */
    public function index()
    {
        return $this->render('administration/admin.html.twig');
    }
}

src/Controller/Administration/ArticleController.php
<?php

namespace App\Controller\Administration;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Manager\ArticleManager;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods="GET")
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('administration/article/index.html.twig', ['articles' => $articleRepository->findAll()]);
    }

    /**
     * @Route("/new", name="article_new", methods="GET|POST")
     */
    public function new(Request $request, ArticleManager $articleManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $articleManager->createArticle($article);
            $this->addFlash('success',"Articlé créé !");
            return $this->redirectToRoute('article_index');
        }

        return $this->render('administration/article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods="GET")
     */
    public function show(Article $article): Response
    {
        return $this->render('administration/article/show.html.twig', ['article' => $article]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods="GET|POST")
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_edit', ['id' => $article->getId()]);
        }

        return $this->render('administration/article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods="DELETE")
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($article);
            $em->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

src/Controller/Administration/CommentController.php
<?php

namespace App\Controller\Administration;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/comment")
 */
class CommentController extends AbstractController
{
    /**
     * @Route("/", name="comment_index", methods="GET")
     */
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('administration/comment/index.html.twig', ['comments' => $commentRepository->findAll()]);
    }

    /**
     * @Route("/new", name="comment_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('administration/comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comment_show", methods="GET")
     */
    public function show(Comment $comment): Response
    {
        return $this->render('administration/comment/show.html.twig', ['comment' => $comment]);
    }

    /**
     * @Route("/{id}/edit", name="comment_edit", methods="GET|POST")
     */
    public function edit(Request $request, Comment $comment): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('comment_edit', ['id' => $comment->getId()]);
        }

        return $this->render('administration/comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comment_delete", methods="DELETE")
     */
    public function delete(Request $request, Comment $comment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($comment);
            $em->flush();
        }

        return $this->redirectToRoute('comment_index');
    }
}

src/Controller/Administration/GalleryController.php
<?php

namespace App\Controller\Administration;

use App\Entity\Gallery;
use App\Entity\Image;
use App\Form\GalleryType;
use App\Form\ImageType;
use App\Manager\GalleryManager;
use App\Repository\GalleryRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/gallery")
 */
class GalleryController extends AbstractController
{
    /**
     * @Route("/", name="gallery_index", methods="GET")
     */
    public function index(GalleryRepository $galleryRepository): Response
    {
        return $this->render('administration/gallery/index.html.twig', ['galleries' => $galleryRepository->findAll()]);
    }

    /**
     * @Route("/new", name="gallery_new", methods="GET|POST")
     */
    public function new(Request $request, GalleryManager $galleryManager): Response
    {
        $gallery = new Gallery();
        $form = $this->createForm(GalleryType::class, $gallery);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $galleryManager->createGallery($gallery);
            $this->addFlash('success',"Galerie ajoutée !");
            return $this->redirectToRoute('gallery_index');
        }

        return $this->render('administration/gallery/new.html.twig', [
            'gallery' => $gallery,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gallery_show", methods="GET")
     * @ParamConverter("gallery", class="App\Entity\Gallery")
     */
    public function show(Request $request, Gallery $gallery, GalleryManager $galleryManager): Response
    {
        $form = $this->createForm(ImageType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $image = $galleryManager->createImage($form->getData()['filename']);
            $filename = $galleryManager->uploadFile($form->getData()['filename'], $this->getParameter('hb.gallery_image')."/".$gallery->getPath());
            $image->setFilename($filename);
            $gallery->addImage($image);
            $galleryManager->update($image);
            $galleryManager->update($gallery);
            $this->addFlash('success',"Image ajoutée !");
            return $this->redirectToRoute('gallery_show', ['id' => $gallery->getId()]);
        }
        return $this->render('administration/gallery/show.html.twig', ['gallery' => $gallery, 'form' => $form->createView()]);
    }

    /**
     * @Route("/{id}/edit", name="gallery_edit", methods="GET|POST")
     */
    public function edit(Request $request, Gallery $gallery): Response
    {
        $form = $this->createForm(GalleryType::class, $gallery);
        $gallery_images_count = count($gallery->getImages());
        dump($gallery_images_count);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $new_count = $gallery->getImages();
            dump($new_count);
            die;
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('gallery_edit', ['id' => $gallery->getId()]);
        }

        return $this->render('administration/gallery/edit.html.twig', [
            'gallery' => $gallery,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route(path="/add-image-on-gallery", name="add_image_on_gallery", methods="POST")
     * @param Request $request
     * @param GalleryManager $galleryManager
     */
    public function addImageToGallery(Request $request, GalleryManager $galleryManager)
    {
        $form = $this->createForm(ImageType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $image = $galleryManager->createImage($form->getData()['filename']);
            $gallery = $galleryManager->getManager()->getRepository(Gallery::class)->find($request->request->get('add_image_on_gallery_id'));
            $filename = $galleryManager->uploadFile($form->getData()['filename'], $this->getParameter('hb.gallery_image')."/".$gallery->getPath());
            $image->setFilename($filename);
            $gallery->addImage($image);
            $galleryManager->update($image);
            $galleryManager->update($gallery);
            $this->addFlash('success',"Image ajoutée !");
            return $this->redirectToRoute('gallery_show', ['id' => $gallery->getId()]);
        }
        return $this->render(
            'administration/gallery/_add_image.html.twig',
            array(
                'form' => $form->createView()
            )
        );
    }

    /**
     * @Route(path="/remove-image-from-gallery", name="remove_image_from_gallery", methods="POST")
     * @param Request $request
     * @param GalleryManager $galleryManager
     * @return bool|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function removeImageFromGallery(Request $request, GalleryManager $galleryManager)
    {
        if ($request->isMethod("POST")) {
            $image = $galleryManager->getManager()->getRepository(Image::class)->find($request->request->get('image_id'));
            $gallery = $galleryManager->getManager()->getRepository(Gallery::class)->find($request->request->get('gallery_id'));
            $gallery->removeImage($image);
            $galleryManager->removeImageFromApp($image, $this->getParameter('hb.gallery_image')."/".$gallery->getPath());
            $galleryManager->remove($image);
            $galleryManager->update($gallery);
            $this->addFlash('success',"Image supprimée de la galerie !");
            return $this->redirectToRoute('gallery_show', array('id' => $gallery->getId()));
        } else {
            return false;
        }
    }

    /**
     * @Route("/{id}", name="gallery_delete", methods="DELETE")
     */
    public function delete(Request $request, Gallery $gallery, GalleryManager $galleryManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$gallery->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $images = $gallery->getImages();
            foreach ($images as $image) {
                $galleryManager->removeImageFromApp($image, $this->getParameter('hb.gallery_image')."/".$gallery->getPath());
                $gallery->removeImage($image);
            }
            $galleryManager->removeFolder($this->getParameter('hb.gallery_image')."/".$gallery->getPath());
            $em->remove($gallery);
            $em->flush();
            $this->addFlash('success',"Galerie supprimée !");
        }

        return $this->redirectToRoute('gallery_index');
    }
}

src/Controller/GalleryController.php
<?php

namespace App\Controller;

use App\Repository\GalleryRepository;
use App\Service\Blog\Pagination;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class GalleryController extends AbstractController
{
    /**
     * @Route(path="/galerie/{page}",  name="galleries", requirements={"page"="\d+"})
     * @param GalleryRepository $repository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function galleries(GalleryRepository $repository, int $page = 1, Pagination $pagination)
    {
        $perPage = 1;
        $allGalleries = $repository->findAll();
        $nbPages = $pagination->getTotalPages($allGalleries, $perPage);
        $limit = $pagination->getLimit($page, $perPage);
        $offset = $pagination->getOffset($limit, $perPage);
        $galleries = $repository->findBy(
            [],
            ['id' => 'DESC'],
            $limit,
            $offset
        );
        return $this->render(
            'gallery/galleries.html.twig', [
                'galleries' => $galleries,
                'per_page' => $perPage,
                'nb_pages' => $nbPages,
                'page' => $page
            ]
        );
    }

    /**
     * @Route("/galerie/{slug}", name="gallery")
     */
    public function gallery(string $slug, GalleryRepository $repository)
    {
        return $this->render(
            'gallery/gallery.html.twig', [
                'gallery' => $repository->findOneBy(
                    array(
                        'slug' => $slug
                    )
                )
            ]
        );
    }
}

templates/administration/gallery/_add_image.html.twig
{{ form_start(form, {'attr': {'action': path('add_image_on_gallery')}}) }}
    {{ form_row(form.filename) }}
    {{ form_row(form.title) }}
    {{ form_row(form.description) }}
<input type="hidden" name="add_image_on_gallery_id" value="">
<button type="submit" name="add_image_submit">Ajouter une image</button>
{{ form_end(form) }}

templates/administration/gallery/_delete_form.html.twig
<form method="post" action="{{ path('gallery_delete', {'id': gallery.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ gallery.id) }}">
    <button class="btn">Supprimer la galerie</button>
</form>

templates/administration/gallery/_delete_image.html.twig
<form action="{{ path('remove_image_from_gallery') }}" method="post" name="remove_image_form">
	<input type="hidden" name="image_id" value="{{ image.id }}">
	<input type="hidden" name="gallery_id" value="{{ gallery.id }}">
	<button type="submit" name="remove_image_submit">Supprimer l'image</button>
</form>

templates/administration/gallery/_delete_image_gallery_form.html.twig
<form method="post" action="{{ path('image_gallery_delete', {'gallery': gallery.id, 'image': field.vars['value'].id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ field.vars['value'].id) }}">
	<button class="btn">Delete image</button>
</form>

templates/administration/gallery/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name) }}
{% include "administration/gallery/_image_widget.html.twig" %}
<button class="btn" type="submit">{{ button_label|default('Save') }}</button>
{% do form.images.setRendered %}
{{ form_end(form) }}

templates/administration/gallery/_image_widget.html.twig
{% block ImageType_Label %}Ajouter une image{% endblock %}
{% block ImageType_Widget %}
	{{ form_widget(form.images) }}
{% endblock %}

templates/administration/gallery/edit.html.twig
{% extends 'administration/admin.html.twig' %}

{% block title %}Gestion des albums photo{% endblock %}
{% block header %}Modification de l'album du {{ gallery.dateCreation|date('d/m/Y') }}{% endblock %}

{% block body %}
    {{ include('administration/gallery/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('gallery_index') }}">back to list</a>
{% endblock %}

{% block javascripts %}
    <script>
        jQuery(document).ready(function () {
            jQuery('.add_image_collection').click(function (e) {
                var list = jQuery(jQuery(this).attr('data-list'));
                // Try to find the counter of the list
                var counter = list.data('widget-counter') | list.children().length;
                // If the counter does not exist, use the length of the list
                if (!counter) { counter = list.children().length; }

                // grab the prototype template
                var newWidget = list.attr('data-prototype');
                // replace the "__name__" used in the id and name of the prototype
                // with a number that's unique to your emails
                // end name attribute looks like name="contact[emails][2]"
                newWidget = newWidget.replace(/__name__/g, counter);
                // Increase the counter
                counter++;
                // And store it, the length cannot be used if deleting widgets is allowed
                list.data(' widget-counter', counter);

                // create a new list element and add it to the list
                var newElem = jQuery(list.attr('data-widget-image')).html(newWidget);
                newElem.appendTo(list);
            });
            jQuery('.remove_image_item').click(function (e) {
                var id = jQuery(jQuery(this).attr('data-id'));
                console.log(id);
            });
        });
    </script>
{% endblock %}

templates/administration/gallery/index.html.twig
{% extends 'administration/admin.html.twig' %}

{% block title %}Gestion des albums photo{% endblock %}
{% block header %}Gérer les albums photo{% endblock %}

{% block body %}
    <table class="table table-bordered table-responsive-sm">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Slug</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for gallery in galleries %}
            <tr>
                <td>{{ gallery.id }}</td>
                <td>{{ gallery.name }}</td>
                <td>{{ gallery.slug }}</td>
                <td>{{ gallery.dateCreation ? gallery.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('gallery_show', {'id': gallery.id}) }}">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('gallery_new') }}">Create new</a>
{% endblock %}

templates/administration/gallery/new.html.twig
{% extends 'administration/admin.html.twig' %}

{% block title %}Gestion des albums photo{% endblock %}
{% block header %}Ajouter un album photo{% endblock %}

{% block body %}
	{% form_theme form
		'administration/collection/jquery.collection.html.twig'
	%}
    {{ include('administration/gallery/_form.html.twig') }}
    <a href="{{ path('gallery_index') }}">back to list</a>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('admin/js/jquery.collection.js') }}"></script>
    <script>
        $('.image_collection_entry').collection({
            up: '<a href="#" class="btn btn-default"><span class="fa fa-arrow-up"></span></a>',
            down: '<a href="#" class="btn btn-default"><span class="fa fa-arrow-down"></span></a>',
            add: '<a href="#" class="btn btn-default"><span class="fa fa-plus"></span></a>',
            remove: '<a href="#" class="btn btn-default"><span class="fa fa-trash"></span></a>'
        });
    </script>
{% endblock %}

templates/administration/gallery/show.html.twig
{% extends 'administration/admin.html.twig' %}

{% block title %}Gestion des albums photo{% endblock %}
{% block header %}Albums photo du {{ gallery.dateCreation|date('d/m/Y') }}{% endblock %}

{% block body %}
    <table class="table table-responsive-sm table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ gallery.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ gallery.name }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ gallery.slug }}</td>
            </tr>
            <tr>
                <th>Path</th>
                <td>{{ gallery.path }}</td>
            </tr>
            <tr>
                <th>Date creation</th>
                <td>{{ gallery.dateCreation ? gallery.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>
					{% for image in gallery.images %}
                        <img src="{{ asset('uploads/gallery/' ~ gallery.path ~ image.filename) }}"
                             alt="" height="300">
                        {% include('administration/gallery/_delete_image.html.twig') %}
					{% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    {{ render(controller('App\\Controller\\Administration\\GalleryController::addImageToGallery')) }}

    <a href="{{ path('gallery_index') }}">back to list</a>

    {{ include('administration/gallery/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script>
        var remove_image_submit = $("button[name=remove_image_submit]");
        var add_image_submit = $("button[name=add_image_submit]");
        $("input[name=add_image_on_gallery_id]")[0].value = {{ gallery.id }};
        remove_image_submit.click(function (e) {
            e.preventDefault();
            $("form[name=remove_image_form]").submit();
        });
        add_image_submit.click(function (e) {
            e.preventDefault();
            $("form[name=image]").submit();
        });
    </script>
{% endblock %}