src/Entity/Meeting.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;

/**
 * @ApiResource()
 * @ApiFilter(DateFilter::class, properties={"meeting_date": DateFilter::EXCLUDE_NULL})
 * @ORM\Entity(repositoryClass="App\Repository\MeetingRepository")
 */
class Meeting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meeting_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Game", mappedBy="meeting", orphanRemoval=true, cascade={"persist","remove"})
     */
    private $games;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    public function __construct()
    {
        $this->games = new ArrayCollection();
        $this->validated = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMeetingDate(): ?string
    {
        return $this->meeting_date;
    }

    public function setMeetingDate(string $meeting_date): self
    {
        $this->meeting_date = $meeting_date;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->setMeeting($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            // set the owning side to null (unless already changed)
            if ($game->getMeeting() === $this) {
                $game->setMeeting(null);
            }
        }

        return $this;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }
}

src/Entity/Training.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrainingRepository")
 * @ApiResource()
 */
class Training
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    const DATE = "Mercredi";

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Team", inversedBy="training", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $team;

    /**
     * @ORM\Column(type="time")
     */
    private $time_start;

    /**
     * @ORM\Column(type="time")
     */
    private $time_end;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getTimeStart(): ?\DateTimeInterface
    {
        return $this->time_start;
    }

    public function setTimeStart(\DateTimeInterface $time_start): self
    {
        $this->time_start = $time_start;

        return $this;
    }

    public function getTimeEnd(): ?\DateTimeInterface
    {
        return $this->time_end;
    }

    public function setTimeEnd(\DateTimeInterface $time_end): self
    {
        $this->time_end = $time_end;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;


use App\Entity\Message;
use App\Form\MessageType;
use App\Manager\MessageManager;
use App\Repository\GalleryRepository;
use App\Repository\GameRepository;
use App\Repository\MeetingRepository;
use App\Repository\SlideRepository;
use App\Repository\TrainingRepository;
use App\Service\Helpers\DateHelper;
use App\Service\Mail\Mailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route(path="/", name="index")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(SlideRepository $slideRepository, MeetingRepository $meetingRepository, DateHelper $date)
    {
        $saturday = $date->getNextSaturday();
        $prev_saturday = $date->getPreviousSaturday();
        $prev_saturday = preg_replace("/-/", "/", $prev_saturday);
        $slides = $slideRepository->findAll();
        $last_meeting = $meetingRepository->findLastMeeting($prev_saturday);
        $next_meeting = $meetingRepository->findNextMeeting($saturday);
        dump($prev_saturday);
        dump($saturday);
        dump($last_meeting);
        dump($next_meeting);
        return $this->render(
            'default/index.html.twig', [
                'slides' => $slides,
                'next_meeting' => $next_meeting,
                'last_meeting' => $last_meeting
            ]
        );
    }

    /**
     * @Route(path="/entrainements", name="trainings")
     * @param TrainingRepository $repository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function trainings(TrainingRepository $repository)
    {
        return $this->render(
            'default/trainings.html.twig', [
                'trainings' => $repository->findAll()
            ]
        );
    }

    /**
     * @Route(path="/contact", name="contact")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function contact(Request $request, MessageManager $messageManager, Mailer $mailer)
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // save message in db
            $messageManager->update($message);
            // send email
            $mailer->sendMessage($message);
            // flash message
            $this->addFlash('success',"Message envoyé !");
            // redirection
            return $this->redirectToRoute('contact');
        }
        return $this->render(
            'default/contact.html.twig', [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * @Route(path="/mentions-legales", name="mentions")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function mentions()
    {
        return $this->render('default/mentions.html.twig');
    }
}

templates/default/contact.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/contact.css') }}">
{% endblock %}

{% block body %}
	<div class="page__header">
		<h1>Nous contacter</h1>
	</div>
	<section class="contact__container flex_column">
		<nav id="contact_tab" role="tablist">
			<div class="nav nav-tabs" id="nav-tab" role="tablist">
				<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Coordonnées</a>
				<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Formulaire</a>
			</div>
		</nav>
		<div class="tab-content" id="nav-tabContent">
			<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
				<section class="contact__informations">
					<h2>Association du club de Handball de Forges-les-Eaux</h2>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium atque dolorum eos exercitationem minima praesentium, quas recusandae sit? Adipisci beatae deleniti ipsa modi, natus quidem reiciendis repellendus repudiandae vitae voluptate.
					</p>
					<section class="contact__info__coords">
						<div class="coords__address">
							<a href="https://www.openstreetmap.org/?mlat=49.61261&amp;mlon=1.53518#map=17/49.61261/1.53518" target="_blank" class="btn btn-outline-dark">
								<i class="fa fa-map"></i>
								<span>Boulevard Madame de Sévigné  Forges les Eaux</span>
							</a>
						</div>
						<div class="coords__phone">
							<a href="tel:0685713590" class="btn btn-outline-primary">
								<i class="fa fa-phone"></i>
								<span>06 85 71 35 90</span>
							</a>
						</div>
						<div class="coords__email">
							<a href="mailto:forgesleseauxhand@gmail.com" class="btn btn-outline-info">
								<i class="fa fa-envelope"></i>
								<span>forgesleseauxhand@gmail.com</span>
							</a>
						</div>
					</section>
				</section>
			</div>
			<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
				<section class="contact__form">
					{{ form_start(form) }}
						<fieldset class="form-group">
							{{ form_label(form.name) }}
							{{ form_widget(form.name) }}
						</fieldset>
						<fieldset class="form-group">
							{{ form_label(form.email) }}
							{{ form_widget(form.email) }}
						</fieldset>
						<fieldset class="form-group">
							{{ form_label(form.subject) }}
							{{ form_widget(form.subject) }}
						</fieldset>
						<fieldset class="form-group">
							{{ form_label(form.message) }}
							{{ form_widget(form.message) }}
						</fieldset>
						<fieldset class="form-group">
							<button type="submit" class="btn btn-primary col-sm-12">Envoyer</button>
						</fieldset>
					{{ form_end(form) }}
				</section>
			</div>
		</div>
	</section>
{% endblock %}

templates/default/header.html.twig
<header class="debug flex_row">
	<div class="header__logo debug">
		<img src="{{ asset('build/images/logo.751d0cb0.png') }}" alt="">
	</div>
	<div class="header__menu_button">
		<button @click="toggleMenu()">
			<i class="fa" :class="class_name"></i>
		</button>
	</div>
</header>
<section class="main__navigation__overlay flex_row" v-if="menu">
	<div class="overlay__menu__container flex_column">
		<div class="navigation__container">
			<nav class="flex_column">
				<a href="{{ path('index') }}">Accueil</a>
				<a href="{{ path('trainings') }}">Entrainements</a>
				<a href="{{ path('matchs') }}">Matchs</a>
				<a href="{{ path('results') }}">Résultats</a>
				<a href="{{ path('galleries') }}">Galerie</a>
				<a href="{{ path('blog') }}">Actualités</a>
				<a href="{{ path('contact') }}">Contact</a>
				<a href="{{ path('register') }}">Inscription</a>
				<a href="{{ path('login') }}">Connexion</a>
				<a href="{{ path('ask_for_password_reinitialisation') }}">Réinitialiser mon mot de passe</a>
			</nav>
		</div>
	</div>
</section>

templates/default/index.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/home.css') }}">
{% endblock %}
{% block body %}
	{% if slides is defined and slides|length != 0 %}
		{% include "default/home/_slider.html.twig" %}
	{% endif %}
	<div id="react_hello_root"></div>
	{% if last_meeting is defined and last_meeting is not null %}
		<div class="page__header">
			<h2>Resultats des matchs du {{ last_meeting.meetingDate }}</h2>
		</div>
		<section class="container">
			<div class="last__results flex_row">
				{% include "default/home/_result_table.html.twig" %}
			</div>
		</section>
	{% endif %}
	{% if next_meeting is defined and next_meeting is not null %}
		<div class="page__header">
			<h2>Prochains matchs le {{ next_meeting.meetingDate }}</h2>
		</div>
		<section class="flex_row container home__next__matchs">
			{% set games = next_meeting.games %}
			{% include "default/home/_next_matchs.html.twig" %}
		</section>
	{% endif %}
{% endblock %}
{% block javascripts %}
	<script src="{{ asset('build/home_js.js') }}"></script>
{% endblock %}

templates/default/mentions.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="page__header">
		<h1>Mentions légales</h1>
	</div>
	<div class="container">
		<h3>1. Présentation du site.</h3>
		<p>En vertu de l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, il est précisé aux utilisateurs du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> l'identité des différents intervenants dans le cadre de sa réalisation et de son suivi :</p>
		<p><strong>Propriétaire</strong> : Olivier BRUYNINX – Association loi 1901 – Boulevard Madame de Sévigné  Forges les Eaux<br />
			<strong>Créateur</strong>  : <a href="www.louisthomas.fr">Louis THOMAS</a><br />
			<strong>Responsable publication</strong> : Gaëtan BOISNARD – boisnard.gaetan@yahoo.fr<br />
			Le responsable publication est une personne physique ou une personne morale.<br />
			<strong>Webmaster</strong> : Louis THOMAS – contact@louisthomas.fr<br />
			<strong>Hébergeur</strong> : o2switch – RCS Clermont Ferrand<br />
			Crédits : Gaëtan BOISNARD
			Louis THOMAS<br />
			Le modèle de mentions légales est offert par Subdelirium.com <a target="_blank" href="https://www.subdelirium.com/generateur-de-mentions-legales/" alt="Modèle de mentions légales">Modèle de mentions légales</a></p>

		<h3>2. Conditions générales d’utilisation du site et des services proposés.</h3>
		<p>L’utilisation du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> sont donc invités à les consulter de manière régulière.</p>
		<p>Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par Olivier BRUYNINX, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.</p>
		<p>Le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> est mis à jour régulièrement par Gaëtan BOISNARD. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.</p>
		<h3>3. Description des services fournis.</h3>
		<p>Le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> a pour objet de fournir une information concernant l’ensemble des activités de la société.</p>
		<p>Olivier BRUYNINX s’efforce de fournir sur le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> des informations aussi précises que possible. Toutefois, il ne pourra être tenue responsable des omissions, des inexactitudes et des carences dans la mise à jour, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</p>
		<p>Tous les informations indiquées sur le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
		<h3>4. Limitations contractuelles sur les données techniques.</h3>
		<p>Le site utilise la technologie JavaScript.</p>
		<p>Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour</p>
		<h3>5. Propriété intellectuelle et contrefaçons.</h3>
		<p>Olivier BRUYNINX est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels.</p>
		<p>Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de : Olivier BRUYNINX.</p>
		<p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
		<h3>6. Limitations de responsabilité.</h3>
		<p>Olivier BRUYNINX ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site http://www.forgesleseauxhandball.fr/, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.</p>
		<p>Olivier BRUYNINX ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a>.</p>
		<p>Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. Olivier BRUYNINX se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, Olivier BRUYNINX se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…).</p>
		<h3>7. Gestion des données personnelles.</h3>
		<p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
		<p>A l'occasion de l'utilisation du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a>, peuvent êtres recueillies : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a>, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur.</p>
		<p> En tout état de cause Olivier BRUYNINX ne collecte des informations personnelles relatives à l'utilisateur que pour le besoin de certains services proposés par le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a>. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> l’obligation ou non de fournir ces informations.</p>
		<p>Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
		<p>Aucune information personnelle de l'utilisateur du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat de Olivier BRUYNINX et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a>.</p>
		<p>Le site n'est pas déclaré à la CNIL car il ne recueille pas d'informations personnelles. .</p>
		<p>Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
		<h3>8. Liens hypertextes et cookies.</h3>
		<p>Le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de Olivier BRUYNINX. Cependant, Olivier BRUYNINX n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</p>
		<p>La navigation sur le site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.</p>
		<p>Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies :</p>
		<p>Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialité et choisissez Bloquer tous les cookies. Validez sur Ok.</p>
		<p>Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l'onglet Options. Cliquer sur l'onglet Vie privée.
			Paramétrez les Règles de conservation sur :  utiliser les paramètres personnalisés pour l'historique. Enfin décochez-la pour  désactiver les cookies.</p>
		<p>Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur Paramètres de contenu. Dans la section "Cookies", vous pouvez bloquer les cookies.</p>
		<p>Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur préférences.  Dans l'onglet "Confidentialité", vous pouvez bloquer les cookies.</p>

		<h3>9. Droit applicable et attribution de juridiction.</h3>
		<p>Tout litige en relation avec l’utilisation du site <a href="http://http://www.forgesleseauxhandball.fr//">http://www.forgesleseauxhandball.fr/</a> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.</p>
		<h3>10. Les principales lois concernées.</h3>
		<p>Loi n° 78-17 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l'informatique, aux fichiers et aux libertés.</p>
		<p> Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.</p>
		<h3>11. Lexique.</h3>
		<p>Utilisateur : Internaute se connectant, utilisant le site susnommé.</p>
		<p>Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l'identification des personnes physiques auxquelles elles s'appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</p>
	</div>
{% endblock %}

templates/default/trainings.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/trainings.css') }}">
{% endblock %}

{% block body %}
	<div class="page__header">
		<h1>Les entraînements</h1>
	</div>
	<section class="container result__container">
	<div class="result__row">
		{% for t in trainings %}
			<div class="result__item">
				<div class="result__team">
					<p>{{ t.team.name }}</p>
					<div class="result__angle"></div>
				</div>
				<div class="result__training">Mercredi - {{ t.timeStart|date('H:i') }} -> {{ t.timeEnd|date('H:i') }}</div>
			</div>
		{% endfor %}
	</div>
	</section>
{% endblock %}