src/Entity/Game.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 * @ApiResource()
 */
class Game
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $opponent;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $winner;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $looser;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank()
     */
    private $winner_score;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank()
     */
    private $looser_score;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="games")
     */
    private $team;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $appointment_location;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $appointment_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Meeting", inversedBy="games", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $meeting;

    /**
     * @ORM\Column(type="boolean")
     */
    private $canceled;

    public function __construct()
    {
        $this->canceled = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getOpponent(): ?string
    {
        return $this->opponent;
    }

    public function setOpponent(string $opponent): self
    {
        $this->opponent = $opponent;

        return $this;
    }

    public function getWinner(): ?string
    {
        return $this->winner;
    }

    public function setWinner(?string $winner): self
    {
        $this->winner = $winner;

        return $this;
    }

    public function getLooser(): ?string
    {
        return $this->looser;
    }

    public function setLooser(?string $looser): self
    {
        $this->looser = $looser;

        return $this;
    }

    public function getWinnerScore(): ?int
    {
        return $this->winner_score;
    }

    public function setWinnerScore(?int $winner_score): self
    {
        $this->winner_score = $winner_score;

        return $this;
    }

    public function getLooserScore(): ?int
    {
        return $this->looser_score;
    }

    public function setLooserScore(?int $looser_score): self
    {
        $this->looser_score = $looser_score;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getAppointmentLocation(): ?string
    {
        return $this->appointment_location;
    }

    public function setAppointmentLocation(string $appointment_location): self
    {
        $this->appointment_location = $appointment_location;

        return $this;
    }

    public function getAppointmentDate(): ?\DateTimeInterface
    {
        return $this->appointment_date;
    }

    public function setAppointmentDate(\DateTimeInterface $appointment_date): self
    {
        $this->appointment_date = $appointment_date;

        return $this;
    }

    public function getMeeting(): ?Meeting
    {
        return $this->meeting;
    }

    public function setMeeting(?Meeting $meeting): self
    {
        $this->meeting = $meeting;

        return $this;
    }

    public function getCanceled(): ?bool
    {
        return $this->canceled;
    }

    public function setCanceled(bool $canceled): self
    {
        $this->canceled = $canceled;

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\Team;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'team',
                EntityType::class,
                array(
                    'class' => Team::class,
                    'choice_label' => 'name',
                    'label' => "L'équipe qui va jouer"
                )
            )
            ->add(
                'opponent',
                TextType::class,
                array(
                    'label' => "L'équipe adverse"
                )
            )
            ->add(
                'location',
                TextType::class,
                array(
                    'label' => "Le lieu du match"
                )
            )
            ->add(
                'appointmentLocation',
                TextType::class,
                array(
                    'label' => "Le lieu du rendez-vous"
                )
            )
            ->add(
                'appointmentDate',
                DateTimeType::class,
                array(
                    'label' => "La date et l'heure du rendez-vous"
                )
            )
            ->add(
                'canceled',
                CheckboxType::class,
                array(
                    'label' => "Cochez si match annulé",
                    'required' => false
                )
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Repository\GameRepository;
use App\Repository\MeetingRepository;
use App\Service\Blog\Pagination;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class GameController extends AbstractController
{
    /**
     * @Route(path="/matchs/{page}", name="games", requirements={"page"="\d+"})
     * @param GameRepository $repository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function games(GameRepository $repository, int $page = 1, Pagination $pagination)
    {
        $perPage = 1;
        $allGames = $repository->findAll();
        $nbPages = $pagination->getTotalPages($allGames, $perPage);
        $limit = $pagination->getLimit($page, $perPage);
        $offset = $pagination->getOffset($limit, $perPage);
        $games = $repository->findBy(
            [],
            ['id' => 'DESC'],
            $limit,
            $offset
        );
        return $this->render(
            'game/games.html.twig', [
                'games' => $games,
                'per_page' => $perPage,
                'nb_pages' => $nbPages,
                'page' => $page
            ]
        );
    }

    /**
     * @Route(path="/resultats/{page}", name="results", requirements={"page"="\d+"})
     * @param GameRepository $repository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function results(MeetingRepository $repository, int $page = 1, Pagination $pagination)
    {
        $perPage = 1;
        $allResults = $repository->findAll();
        $nbPages = $pagination->getTotalPages($allResults, $perPage);
        $limit = $pagination->getLimit($page, $perPage);
        $offset = $pagination->getOffset($limit, $perPage);
        $meetings = $repository->findBy(
            [],
            ['id' => 'DESC'],
            $limit,
            $offset
        );
        return $this->render(
            'game/results.html.twig', [
                'meetings' => $meetings,
                'per_page' => $perPage,
                'nb_pages' => $nbPages,
                'page' => $page
            ]
        );
    }
}

templates/game/games.html.twig
{% extends "base.html.twig" %}

{% block body %}
	matchs
	{{ dump(games) }}

	<nav aria-label="Page navigation example">
		<ul class="pagination">
			{% if page > 1 %}
				<li class="page-item"><a class="page-link" href="{{ path('games', {'page': page-1}) }}">Previous</a></li>
			{% endif %}
			{% for i in 1..nb_pages %}
				{% if page == i %}
					<li class="page-item active"><a href="{{ path('games', {'page': i}) }}" class="page-link">{{ i }}</a></li>
				{% else %}
					<li class="page-item"><a href="{{ path('games', {'page': i}) }}" class="page-link">{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if page < nb_pages %}
				<li class="page-item"><a class="page-link" href="{{ path('games', {'page': page+1}) }}">Next</a></li>
			{% endif %}
		</ul>
	</nav>
{% endblock %}

templates/game/results.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/results.css') }}">
{% endblock %}
{% block body %}
	<div class="page__header">
		<h1>Resultats des matchs</h1>
	</div>
	<section class="container">
		<div class="last__results">
			{% include 'game/results_table.html.twig' %}
		</div>
	</section>
{% endblock %}

templates/game/results_table.html.twig
<table class="table table-striped">
	<thead class="thead-light"> <!-- add class="thead-light" for a light header -->
	<tr>
		<th scope="col" class="filter-select filter-exact" data-placeholder="Sélectionnez une équipe">Équipe de Forges
		</th>
		<th scope="col" class="filter-select filter-exact" data-placeholder="Sélectionnez l'adversaire">Adversaire</th>
		<th scope="col" class="filter-select filter-exact" data-placeholder="Sélectionnez une équipe">Victoire</th>
		<th scope="col" class="sorter-false filter-false">Score</th>
	</tr>
	</thead>
	<tbody>
	{% for m in meetings %}
		{% for g in m.games %}
			<tr>
				<td scope="row">{{ g.team.name }}</td>
				<td>{{ g.opponent }}</td>
				<td>{{ g.winner }}</td>
				<td>{{ g.winnerScore }} - {{ g.looserScore }}</td>
			</tr>
		{% endfor %}
	{% endfor %}
	</tbody>
	<tfoot>
	<tr>
		<th scope="col">Équipe de Forges</th>
		<th scope="col">Adversaire</th>
		<th scope="col">Victoire</th>
		<th scope="col">Score</th>
	</tr>
	<tr>
		<th colspan="4" class="ts-pager">
			<div class="form-inline">
				<div class="btn-group btn-group-sm mx-1" role="group">
					<button type="button" class="btn btn-secondary first" title="first">⇤</button>
					<button type="button" class="btn btn-secondary prev" title="previous">←</button>
				</div>
				<span class="pagedisplay"></span>
				<div class="btn-group btn-group-sm mx-1" role="group">
					<button type="button" class="btn btn-secondary next" title="next">→</button>
					<button type="button" class="btn btn-secondary last" title="last">⇥</button>
				</div>
				<select class="form-control-sm custom-select px-1 pagesize" title="Select page size">
					<option selected="selected" value="10">10</option>
					<option value="20">20</option>
					<option value="30">30</option>
					<option value="all">All Rows</option>
				</select>
				<button type="button" class="btn btn-outline-danger reset">Réinitialiser les filtres</button>
			</div>
		</th>
	</tr>
	</tfoot>
</table>